// Copyright (c) 2023, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:google_cloud_storage/shim')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ShimClient Function()>()
external ShimClient createClient();

@ffi.Native<ffi.Void Function(ShimClient)>()
external void destroyClient(ShimClient client);

@ffi.Native<
  ffi.Void Function(
    ShimClient,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>,
  )
>()
external void createBucket(
  ShimClient shim_client,
  ffi.Pointer<ffi.Char> bucket_name,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> callback,
);

@ffi.Native<
  ShimObjectWriteStream Function(
    ShimClient,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ShimObjectWriteStream writeObject(
  ShimClient client,
  ffi.Pointer<ffi.Char> bucket_name,
  ffi.Pointer<ffi.Char> object_name,
);

@ffi.Native<
  ffi.Int Function(ShimObjectWriteStream, ffi.Pointer<ffi.Char>, ffi.Int)
>()
external int writeChunk(
  ShimObjectWriteStream writer,
  ffi.Pointer<ffi.Char> data,
  int size,
);

@ffi.Native<ffi.Void Function(ShimObjectWriteStream)>()
external void destroyWriter(ShimObjectWriteStream writer);

final class ShimClient extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _client;
}

final class ShimObjectWriteStream extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _writer;
}
