name: Health

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@a3cf960b1206cedc91e5583d5143f66395440041
    with:
      checks: "license,breaking,do-not-submit,leaking"
    permissions:
      pull-requests: write
