name: Health

# Run on PRs and pushes to the default branch.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@a3cf960b1206cedc91e5583d5143f66395440041
    with:
      checks: "license,breaking,do-not-submit,leaking"
    permissions:
      pull-requests: write
